### ISSUE TITLE
Syncing sometimes duplicates files

### ISSUE THREAD

**Issue by axel22** [bcedu/VGrive#42]
I installed VGrive today, and it's still syncing.
There were multiple occurrences of duplicated files.
Here is one such example:

![screenshot-01-15-24](https://user-images.githubusercontent.com/151774/68094439-b36d0680-fea0-11e9-9ca2-5cf3b1f837a1.png)

This is followed in the log with a message like this:

```
DELETE LOCAL FILE: <...filename...>.pdf
```

**Comment by bcedu** [comment]
Did you initially started VGrive in a folder where there were files? Or you selected/created an empty folder? 

If you started the sync process in a folder where, for example, the file `14.pdf` already existed, the sync process will detect the local copy of `14.pdf` different from the copy from google drive.

If this is not the case (you started in an empty/new folder), maybe the library file (where VGrive store information about synced files) is corrupted. Try to log out and start the sync process in a new directory to start a "clean process".

Finnally, if the problem still persist, I will need you to tell me the exact files structure you are trying to sync. For example, in the google drive the file structure is:

- aFolderName
    - File_1.txt
    - File_2.txt
    - 14.pdf
- AnotherFolder
    - AnotherFile.png

Obyously I don't need the files content, only the structure of the files and their names. Because I've not been able to replicate the bug.

**Comment by axel22** [comment]
> Did you initially started VGrive in a folder where there were files? Or you selected/created an empty folder?

I installed VGrive using the debian package.
The default folder was `vGrive` and it was created by VGrive - it did not exist before.

> If you started the sync process in a folder where, for example, the file 14.pdf already existed, the sync process will detect the local copy of 14.pdf different from the copy from google drive.

There is a possibility that vGrive closed in the background, and this started happening after I restarted it (i.e. https://github.com/bcedu/VGrive/issues/43).

I will try a clean sync in a new dir if this keeps happening, and then follow up.

**Comment by bcedu** [comment]
Did the clean installation solved the problem?

**Comment by bcedu** [comment]
I close this issue . The newest version has solved some bugs about detecting existing files and after some test this issue looks solved. If the problem persists reopen this issue. Thanks! :smile:
